### ISSUE TITLE
Womegle help

### ISSUE THREAD

**Issue by duchnoun** [mateusabelli/omedev#1]
Hope this message finds you all coding away in high spirits! I've landed in a bit of a conundrum while fine-tuning my project, womegle.com – a project spun from the realms of Omegle. My scripting journey has been quite the rollercoaster, and now, I'm stuck on a rather peculiar RTCP PeerConnection snag.

Tech Challenge Unveiled:

Upon receiving ICE from the STUN server, it appears the RTCP PeerConnection is being a bit finicky, hesitating to accept the offerings. This, needless to say, is throwing a wrench in the gears of my otherwise smoothly running website.

Cry for Collective Brainpower:

So here I am, extending a digital SOS to this vibrant community, hoping for a burst of wisdom and perhaps a sprinkle of collaborative magic. If anyone out there has danced with a similar coding devil or possesses the mystical knowledge of RTCP PeerConnection behavior, your mentorship would be my beacon.

Steps to Replicate the Quirk:

Pay a virtual visit to womegle.com.
Initiate a rendezvous.
Observe the RTCP PeerConnection raising eyebrows at ICE from the STUN server.

**Comment by mateusabelli** [comment]
Hello @duchnoun I hope you're doing well.
You have a nice project there! I'm sorry but I don't think I'll be able to help with this issue, when I built this app I didn't used the same tech as yours so I am not quite familiar with it.
